version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: tournament_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tournament
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: tournament_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
